const express = require("express");
const cors = require("cors");
require("dotenv").config({ path: require("path").join(__dirname, ".env") });
const { initDb, getAllEmissions, insertEmissionRecord, findUserByEmail, companyExists, getEmissionsReport, getDashboardData, seedUsers } = require("./db");
const { calculateEmissions } = require("./calculationEngine");
const { hashPassword, verifyPassword, signToken, requireAuth } = require("./auth");
const app = express(); const PORT = Number(process.env.PORT || 4000);
const VALID_UNITS = { "Purchased Electricity":["kWh","MWh"], "Fleet & Fuel":["L","liters"], Facilities:["m³","m3"], "Business Travel":["passenger-km"], "Purchased Goods":["tons","tonnes"], "Logistics & Freight":["shipments"], Other:["unit","units"] };
app.use(cors({ origin: /^http:\/\/localhost(:\d+)?$/, credentials: true, allowedHeaders:["Content-Type","Authorization"] })); app.use(express.json());
const publicUser = u => ({ id:u.id, email:u.email, role:u.role, companyId:u.companyId });
function resolveCompany(req,res) { const requested=req.query.companyId || req.body?.companyId; if(req.user.role === "ADMIN") return requested || null; if(requested && requested !== req.user.companyId){res.status(403).json({success:false,error:"You are not authorized to access another company's data."});return undefined;} return req.user.companyId; }
function validateInput(b){ const e={}, n=Number(b.consumption); if(!Number.isFinite(n)||n<=0)e.consumption="Consumption must be a valid positive number."; if(!b.category||!VALID_UNITS[b.category])e.category="A supported emission category is required."; if(!b.unit||!VALID_UNITS[b.category]?.includes(String(b.unit).trim()))e.unit="The unit is not valid for the selected category."; if(!b.facility?.trim())e.facility="Facility is required."; if(!b.reportingPeriod?.trim())e.reportingPeriod="Reporting period is required."; return e; }
function recordFromCalculation(c,companyId){return {id:`rec-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,companyId,date:new Date().toISOString(),activity:c.activity,scope:c.scope,category:c.category,quantity:`${c.input} ${c.unit}`,emissions:c.resultTonnes>=1?`${c.resultTonnes.toFixed(2)} tCO₂e`:`${c.resultKg.toFixed(2)} kg CO₂e`,status:"Verified",facility:c.facility,conversionFactor:c.conversionFactor,inputUnit:c.unit,isNew:true};}
app.get(["/health","/api/health"],(_q,res)=>res.json({status:"healthy",service:"ecotrack-backend",database:"postgresql"}));
app.post("/api/auth/login",async(req,res,next)=>{try{const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!email||!password)return res.status(400).json({success:false,error:"Email and password are required."});const user=await findUserByEmail(email);if(!user||!verifyPassword(password,user.passwordHash))return res.status(401).json({success:false,error:"Invalid email or password."});res.json({success:true,data:{user:publicUser(user),token:signToken(user)}});}catch(e){next(e);}});
app.post("/api/emissions/calculate",requireAuth,(req,res)=>{const errors=validateInput(req.body||{});if(Object.keys(errors).length)return res.status(400).json({success:false,error:"Validation error.",details:errors});try{res.json({success:true,data:calculateEmissions(req.body)});}catch{res.status(400).json({success:false,error:"Unable to calculate emissions."});}});
app.get("/api/emissions",requireAuth,async(req,res,next)=>{try{const companyId=resolveCompany(req,res);if(companyId===undefined)return;const records=await getAllEmissions({...req.query,companyId});res.json({success:true,data:{records,total:records.length}});}catch(e){next(e);}});
app.post("/api/emissions",requireAuth,async(req,res,next)=>{try{const companyId=resolveCompany(req,res);if(companyId===undefined)return;if(!companyId)return res.status(400).json({success:false,error:"Admins must select a companyId when creating an emission."});if(!(await companyExists(companyId)))return res.status(404).json({success:false,error:"Company not found."});const input=req.body?.input!==undefined?{...req.body,consumption:Number(String(req.body.input).replace(/,/g,""))}:req.body;const errors=validateInput(input||{});if(Object.keys(errors).length)return res.status(400).json({success:false,error:"Validation error.",details:errors});const calculation=calculateEmissions(input),record=recordFromCalculation(calculation,companyId);await insertEmissionRecord(record,calculation);res.status(201).json({success:true,message:"Emission record saved successfully.",data:{record,calculation}});}catch(e){next(e);}});
app.get("/api/reports",requireAuth,async(req,res,next)=>{try{const companyId=resolveCompany(req,res);if(companyId===undefined)return;if(!companyId)return res.status(400).json({success:false,error:"Admins must select a companyId for reports."});if(!(await companyExists(companyId)))return res.status(404).json({success:false,error:"Company not found."});const month=typeof req.query.month === "string" ? req.query.month : null;const year=typeof req.query.year === "string" ? req.query.year : null;if(month&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))return res.status(400).json({success:false,error:"month must use YYYY-MM format."});if(year&&!/^\d{4}$/.test(year))return res.status(400).json({success:false,error:"year must use YYYY format."});if(month&&year)return res.status(400).json({success:false,error:"Specify either month or year, not both."});const report=await getEmissionsReport(companyId,{month,year});const label=month||year||"All recorded periods";res.json({success:true,data:{companyId,period:{from:month?`${month}-01`:year?`${year}-01-01`:null,to:month?`${month}-31`:year?`${year}-12-31`:null,label},...report}});}catch(e){next(e);}});
app.get("/api/dashboard",requireAuth,async(req,res,next)=>{try{const companyId=resolveCompany(req,res);if(companyId===undefined)return;if(!companyId)return res.status(400).json({success:false,error:"Admins must select a companyId for the dashboard."});if(!(await companyExists(companyId)))return res.status(404).json({success:false,error:"Company not found."});const period=typeof req.query.period === "string" ? req.query.period : "Current Period";if(!["Current Period","Q2 2026","Q1 2026","Full Year 2025"].includes(period))return res.status(400).json({success:false,error:"Unsupported dashboard period."});res.json({success:true,data:await getDashboardData(companyId,period)});}catch(e){next(e);}});
app.use((_q,res)=>res.status(404).json({success:false,error:"Route not found."})); app.use((e,_q,res,_n)=>{console.error("Backend error:",e.message);res.status(500).json({success:false,error:"Unexpected server error."});});
async function start(){await initDb();const password=process.env.SEED_PASSWORD||"EcoTrackDemo!2026";await seedUsers([{id:"usr-admin-david",email:"admin@ecotrack.test",passwordHash:hashPassword(password),role:"ADMIN",companyId:null},{id:"usr-company-a",email:"companya@ecotrack.test",passwordHash:hashPassword(password),role:"COMPANY_USER",companyId:"company-a"},{id:"usr-company-b",email:"companyb@ecotrack.test",passwordHash:hashPassword(password),role:"COMPANY_USER",companyId:"company-b"}]);app.listen(PORT,()=>console.log(`EcoTrack backend listening on port ${PORT}`));}
if(require.main===module)start().catch(e=>{console.error("Backend startup failed:",e.message);process.exit(1);}); module.exports={app,start,VALID_UNITS};
